apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web 
  template:
    metadata:
      labels: 
        app: web
    spec:
      containers:
      - name: go-k8s-example
        image: felipes102/go-k8s-example:2.1
        envFrom:
          - configMapRef:
              name: test-env
        ports:
          - containerPort: 8080
    


---

apiVersion: v1
kind: Service
metadata:
  name: go-api-service
spec:
  selector:
    app: web 
  ports:
  - protocol: TCP
    port: 8080
  type: ClusterIP