apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web 
  template:
    metadata:
      labels: 
        app: web
    spec:
      containers:
      - name: go-k8s-example
        image: "felipes102/go-k8s-example:3.5"

        resources:
          requests:
            cpu: 200m
            memory: 20Mi
          limits: 
            cpu: 400m
            memory: 25Mi

        livenessProbe: 
          httpGet:
            path: /health
            port: 8080
          periodSeconds: 3
          failureThreshold: 1
          timeoutSeconds: 2
          initialDelaySeconds: 15
        readinessProbe: 
          httpGet:
            path: /health
            port: 8080
          periodSeconds: 3
          failureThreshold: 1
        envFrom:
          - configMapRef:
              name: test-env
        volumeMounts:
          - mountPath: "/go/pvclaim"
            name: server-volume
        ports:
          - containerPort: 8080
      volumes:
        - name: server-volume
          persistentVolumeClaim:
            claimName: server-pvc

    
---

apiVersion: v1
kind: Service
metadata:
  name: go-api-service
spec:
  selector:
    app: web 
  ports:
  - protocol: TCP
    port: 8080
  type: ClusterIP